Check for sufficient space in /boot
upgrades-migrations/redhat-upgrade-tool pull request #19
Opened 2017-05-18 19:34 UTC by bocekm

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1361219
- installation of kernel and grub during the upgrade requires certain amount of space in /boot. The available space left is checked after the initramfs and kernel are downloaded. 50 MB should be enough even with reserve.

2017-05-22 23:34 UTC, AloisMahdal commented on redhat-upgrade-tool.py
> +                         % int(additional_mb_needed))
There's no need to coerce using `int()`, `%d` already does that.

2017-05-22 23:34 UTC, AloisMahdal commented on redhat-upgrade-tool.py
> +                         % int(additional_mb_needed))
Also, why we're using gettext on error message below (l. 451) but not here?

2017-05-22 23:34 UTC, AloisMahdal commented on redhat-upgrade-tool.py
> +                         % int(additional_mb_needed))
Last, but not least: It's not conventional to use SI Mega prefix here. When talking about data, the common convention is "mebibytes", that is, conversion rate 1024 (which can be conveniently written as `2**20`, `2**30`, etc.) and prefix `Mi`.

2017-05-23 09:36 UTC, bocekm commented on redhat-upgrade-tool.py
> +                         % int(additional_mb_needed))
1. I'll remove calling int(), I didn't know that %d does that for me.
2. I'll add calling gettext here. Thanks for catching that.
3. When I ran df -h, I've seen M, so I thought it's mega, but it's mibi actually.
    However, when you run dnf and you don't have enough space, it gives you: "Disk Requirements: At least 32MB more space needed on the /boot filesystem."
    These are the two tools I ran to decide what unit to use, so you can see why I chose mega. But you're right, mega may be perceived as deprecated, I'll use mibi.

2017-05-23 20:11 UTC, bocekm commented on redhat-upgrade-tool.py
> +                         % int(additional_mb_needed))
@AloisMahdal I've done the changes, please check them out.

2017-05-26 16:29 UTC, pirat89 requested changes
I guess there is something wrong, because it prints me just half from the still missing required space.
```
.....
Upgrade test failed with the following problems:
insufficient disk space:
  /boot needs 16M more free space
rpm transaction 100% [======================================================================================================]
[pepaZdepa] #
[pepaZdepa] # df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_rhel6upgrade-lv_root
                      9,2G  2,8G  5,9G  33% /
tmpfs                 939M     0  939M   0% /dev/shm
/dev/vda1             477M  437M   15M  97% /boot
```

2017-05-26 16:36 UTC, pirat89 commented on redhat-upgrade-tool.py
> +            (MIN_AVAIL_BYTES_FOR_BOOT - avail_bytes) / (1024 * 1024)
you should use `2**20` instead of `1024 * 1024` as Lojza pointed. It is more readable to me. But it is just detail.

2017-06-15 14:12 UTC, bocekm commented
@pirat89 The message you reported is not the one I was updating. The `"insufficient disk space: /boot needs 16M more free space"` is actually a message from yum because it has no space left when downloading _initramfs_ (~50MB) and _vmlinuz_ kernel (~5MB). I can't influence this message.

To test my message, leave **just** enough space to let the tool download the images without problem. **Then** if the available space is less than 50MB, my message pops up.

Refrain from using _--cleanup-post_ option to be able to see what has been downloaded and what not.

2017-06-15 14:15 UTC, bocekm commented on redhat-upgrade-tool.py
> +            (MIN_AVAIL_BYTES_FOR_BOOT - avail_bytes) / (1024 * 1024)
Implemented.

2017-06-15 21:45 UTC, bocekm commented on redhat-upgrade-tool.py
> +MIN_AVAIL_BYTES_FOR_BOOT = 50000000
As we have agreed on using MiB, then 50 Mib is 52430000 bytes.

2017-06-15 22:15 UTC, bocekm commented
```
[root@localhost ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
...
tmpfs                 939M     0  939M   0% /dev/shm
/dev/vda1             477M  367M   85M  82% /boot
[root@localhost ~]# redhat-upgrade-tool-cli --cleanup-post --addrepo --instrepo=http://example.com/RHEL-7/7.3/Server/x86_64/os --network 7.3
...
Not enough space. /boot/ needs additional 18 MiB.
[root@localhost ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
...
/dev/vda1             477M  420M   32M  94% /boot
```

2017-06-16 10:51 UTC, pirat89 approved these changes

2017-06-16 11:03 UTC, merged